import Head from 'next/head'
import Image from 'next/image'
import Content from '../containers/Content'
import Header from '../containers/Header'
import Nav from '../containers/Nav'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content />
    

   
    </div>
  )
}
